root = "."
tmp_dir = "tmp"
 
[build]
  cmd = "go build -o ./tmp/main.exe ./cmd"
  bin = "tmp/main.exe"
  pull = true
 
[log]
  level = "debug"
 
[watch]
  include = ["cmd/**", "cmd/**/*.go"]
  exclude = ["tmp", "vendor"]
 