service: "fb"

# mongo:
#   uri:
#   host: "127.0.0.1:28017"
#   username: "phannita016"
#   password: "123456"
#   database: "license"
server:
  address: 0.0.0.0
  port: 8081
  
mongo:
  uri:
  host: "127.0.0.1:27017"
  username: "root"
  password: "password"
  database: "seniorproject"

admin:
  username: "admin"
  password: "P@ssw0rd"